use_frameworks!

target 'RxAlamofire_Example' do
  pod 'RxAlamofire', :path => '../'

  target 'RxAlamofire_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
